### PR TITLE
Disconnect Player When the Bot Gets Manually Disconnected

### LINKED ISSUE #29: is_connected() returns True even if the bot is not connected to a voice channel
`Player._connected` is not updated if the bot is manually disconnected from a voice channel

### PR DESCRIPTION
**Pull request by Makiyu-py**
As requested by @KosmicAnomaly

Closes #29.

### CODE REVIEW

**Comment by Om1609** [comment]
This raises an error if you check the logs
`TypeError: Player.disconnect() missing 1 required keyword-only argument: 'force'`

**Comment by Lulalaby** [comment]
@Om1609 should be fixed in https://github.com/Pycord-Development/Pycord.Wavelink/commit/5dffdba11e34ec50381a5746dea6ad0a750331f0

**Comment by Om1609** [comment]
Cool 👍

**Comment by Om1609** [comment]
Wait hold up

**Comment by Om1609** [comment]
```
  File "/home/container/.local/lib/python3.10/site-packages/pycord/wavelink/player.py", line 156
    await self.disconnect(force: true)
                               ^
SyntaxError: invalid syntax
```

You might wanna test the commits first. This is python 👀. We use `=`

**Pull request merged**
